source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Alamofire',        '~> 4.4'
pod 'Decodable',        '~> 0.5'
pod 'AlamofireImage',   '~> 3.1'

target 'HelloTrello_Example' do
  pod 'TrelloHello', :path => '../'
end

target 'HelloTrello_Tests' do
  pod 'TrelloHello', :path => '../'
end
