source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Alamofire',        '~> 3.0'
pod 'Decodable',        '~> 0.4'
pod 'AlamofireImage',   '~> 2.0'

target 'HelloTrello_Example' do
  pod 'TrelloHello', :path => '../'
end

target 'HelloTrello_Tests' do
  pod 'TrelloHello', :path => '../'
end
